title: "Yitbarek Lab"
description: "Avian Health Biology — University of Delaware"

# Add navigation
header_pages:
  - index.md
  - research.md
  - team.md
  - publications.md
  - courses.md
  - facilities.md
  - open-positions.md
  - contact.md

# Optional: social links
author: Dr. Alex Yitbarek
email: yitbarek@udel.edu

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# Link to custom CSS
include:
  - assets/css/style.css

