title: "Yitbarek Lab"
description: "Avian Health Biology — University of Delaware"
theme: minima

header_pages:
  - Lab News.md
  - research.md
  - team.md
  - courses.md
  - publications.md
  - open-positions.md
  - facilities.md
  - Funding.md
  - Publications1.html



include:
  - assets

author: "Dr. Alex Yitbarek"
email: "yitbarek@udel.edu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
