title: "Yitbarek Lab"
description: "Avian Health Biology — University of Delaware"
remote_theme: just-the-docs/just-the-docs

just_the_docs:
  logo: "/assets/Logo.png"
  favicon_ico: "/assets/favicon.ico"
  color_scheme: light
  search_enabled: true

author: "Dr. Alex Yitbarek"
email: "yitbarek@udel.edu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

include:
  - assets
